receivers:
  practice:
    collection_interval: 5s

exporters:
  debug:
    verbosity: normal
    use_internal_logger: false
    output_paths:
      - stdout
  otlphttp/vmetrics:
    endpoint: http://vm:8428/opentelemetry

service:
  pipelines:
    metrics:
      receivers: [practice]
      exporters:
        - debug
        - otlphttp/vmetrics
  telemetry:
    logs:
      level: error
