receivers:
  practice:
    collection_interval: 5s

exporters:
  debug:
    verbosity: normal
    use_internal_logger: false
    output_paths:
      - stdout

service:
  pipelines:
    metrics:
      receivers: [practice]
      exporters: [debug]
  telemetry:
    logs:
      level: error
