services:
  dev:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/work
    command: sleep infinity
    init: true

  vm:
    image: victoriametrics/victoria-metrics:latest
    restart: unless-stopped
    volumes:
      - victoriametrics-data:/victoria-metrics-data
    command:
      - "-storageDataPath=/victoria-metrics-data"

volumes:
  victoriametrics-data:
