package practicereceiver

import (
	"context"
	"sync/atomic"
	"time"

	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
)

type practiceScraper struct {
	counter int64
}

func newScraper() *practiceScraper {
	return &practiceScraper{}
}

func (s *practiceScraper) scrape(ctx context.Context) (pmetric.Metrics, error) {
	n := atomic.AddInt64(&s.counter, 1)

	md := pmetric.NewMetrics()

	rm := md.ResourceMetrics().AppendEmpty()
	sm := rm.ScopeMetrics().AppendEmpty()

	metric := sm.Metrics().AppendEmpty()
	metric.SetName("practice.value")
	metric.SetDescription("Practice metric generated by custom receiver")

	gauge := metric.SetEmptyGauge()

	dp := gauge.DataPoints().AppendEmpty()
	dp.SetTimestamp(pcommon.NewTimestampFromTime(time.Now()))
	dp.SetIntValue(n)

	return md, nil
}
